basePath: '{{.BasePath}}'
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: '{{.Title}}'
  version: '{{.Version}}'
paths:
  /api/v1/calves:
    get:
      consumes:
      - application/json
      description: 每页20个记录，在路径中添加?page=x表示获取第x页的数据
      parameters:
      - description: 页号
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功会返回id,cow_id,fetus_organ,is_complete,is_abortion,yak_id,yak_index,milk_production,cream,protein,birth_time,flowing_time,fetus_time,fetus_birth_time,placenta_time
          schema:
            type: string
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/string'
            type: object
        "500":
          description: fail
          schema:
            type: string
      summary: 获取一页产犊记录
    post:
      consumes:
      - application/json
      description: 新增产犊记录
      parameters:
      - description: 母牛号
        in: body
        name: cow_id
        required: true
        schema:
          $ref: '#/definitions/int'
          type: object
      - description: 犊牛号
        in: body
        name: yak_id
        required: true
        schema:
          $ref: '#/definitions/int'
          type: object
      - description: 胎衣排出是否完整,只能是1,2
        in: body
        name: is_complete
        required: true
        schema:
          $ref: '#/definitions/int'
          type: object
      - description: 是否流产或者难产,只能是1,2
        in: body
        name: is_abortion
        required: true
        schema:
          $ref: '#/definitions/int'
          type: object
      - description: 露出阴门的胎儿器官
        in: body
        name: fetus_organ
        required: true
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: 分娩日期 格式为2006-01-02 15:04:05 正则表达式严格匹配
        in: body
        name: birth_time
        required: true
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: 阴道开始流水日期 格式为2006-01-02 15:04:05 正则表达式严格匹配
        in: body
        name: flowint_time
        required: true
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: 胎儿露出阴门时间 格式为2006-01-02 15:04:05 正则表达式严格匹配
        in: body
        name: fetus_time
        required: true
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: 胎儿娩出时间
        in: body
        name: fetus_birth_time
        required: true
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: 胎盘排出时间
        in: body
        name: placenta_time
        required: true
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: 犊牛相关指数,未确定计算方法,先任意输入
        in: body
        name: yak_index
        required: true
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: 泌乳期产奶量,未确定计算方法,先任意输入
        in: body
        name: milk_production
        required: true
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: 乳脂量,未确定计算方法,先任意输入
        in: body
        name: cream
        required: true
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: 乳蛋白量,未确定计算方法,先任意输入
        in: body
        name: protein
        required: true
        schema:
          $ref: '#/definitions/string'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: 请求参数错误
          schema:
            type: string
        "10001":
          description: 该记录已经存在
          schema:
            type: string
        "10003":
          description: 时间格式出错
          schema:
            type: string
      summary: 新增产犊记录
  /api/v1/calves/{cow_id}:
    get:
      consumes:
      - application/json
      description: 通过cow_id获取
      parameters:
      - description: 母牛号
        in: path
        name: cow_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "10002":
          description: 该数据不存在
          schema:
            type: string
      summary: 获取产犊记录
  /api/v1/calves/{id}:
    delete:
      consumes:
      - application/json
      description: 通过id删除产犊记录
      parameters:
      - description: 这个id与cow_id不同，是数据库中的自增主键，在请求数据的时候，这个id会发送到前端,可在前端设置隐藏数据保存这个id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: 请求参数错误
          schema:
            type: string
        "10001":
          description: 该记录不存在
          schema:
            type: string
      summary: 删除产犊记录
    put:
      consumes:
      - application/json
      description: 通过id更新数据
      parameters:
      - description: 这个id与cow_id不同，是数据库中的自增主键，在请求数据的时候，这个id会发送到前端,可在前端设置隐藏数据保存这个id
        in: path
        name: id
        required: true
        type: integer
      - description: 母牛号
        in: body
        name: cow_id
        schema:
          $ref: '#/definitions/int'
          type: object
      - description: 犊牛号
        in: body
        name: yak_id
        schema:
          $ref: '#/definitions/int'
          type: object
      - description: 胎衣排出是否完整,只能是1,2
        in: body
        name: is_complete
        schema:
          $ref: '#/definitions/int'
          type: object
      - description: 是否流产或者难产,只能是1,2
        in: body
        name: is_abortion
        schema:
          $ref: '#/definitions/int'
          type: object
      - description: 露出阴门的胎儿器官
        in: body
        name: fetus_organ
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: 分娩日期 格式为2006-01-02 15:04:05 正则表达式严格匹配
        in: body
        name: birth_time
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: 阴道开始流水日期 格式为2006-01-02 15:04:05 正则表达式严格匹配
        in: body
        name: flowint_time
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: 胎儿露出阴门时间 格式为2006-01-02 15:04:05 正则表达式严格匹配
        in: body
        name: fetus_time
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: 胎儿娩出时间
        in: body
        name: fetus_birth_time
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: 胎盘排出时间
        in: body
        name: placenta_time
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: 犊牛相关指数,未确定计算方法,先任意输入
        in: body
        name: yak_index
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: 泌乳期产奶量,未确定计算方法,先任意输入
        in: body
        name: milk_production
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: 乳脂量,未确定计算方法,先任意输入
        in: body
        name: cream
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: 乳蛋白量,未确定计算方法,先任意输入
        in: body
        name: protein
        schema:
          $ref: '#/definitions/string'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: 请求参数错误
          schema:
            type: string
        "10002":
          description: 该记录不存在
          schema:
            type: string
        "10003":
          description: 时间格式出错
          schema:
            type: string
      summary: 更新数据
swagger: "2.0"
